### PR TITLE
Do not reset CUDA context after UCX tests

### LINKED ISSUE #8194: gpu CI failing pretty consistently with segfault
I've noticed gpuCI has been failing pretty consistently (for example, [this build](https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/7578/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.9,RAPIDS_VER=23.10/console) and [this build](https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/7574/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.9,RAPIDS_VER=23.10/console)) with a segfault. Note that tests actually pass -- there must be some extra step where things are going awry 

```
09:26:31 SKIPPED [2] distributed/diagnostics/tests/test_nvml.py:107: Less than two GPUs available
09:26:31 SKIPPED [1] distributed/shuffle/tests/test_shuffle.py:134: could not import 'dask_cudf': No module named 'dask_cudf'
09:26:31 XFAIL distributed/comm/tests/test_ucx.py::test_cuda_context - If running on Docker, requires --pid=host
09:26:31 XFAIL distributed/diagnostics/tests/test_nvml.py::test_has_cuda_context - If running on Docker, requires --pid=host
09:26:31 XFAIL distributed/tests/test_nanny.py::test_no_unnecessary_imports_on_worker[pandas] - distributed#5723
09:26:31 ==== 372 passed, 8 skipped, 3702 deselected, 3 xfailed in 257.84s (0:04:17) ====
09:26:32 continuous_integration/gpuci/build.sh: line 58:   173 Segmentation fault      (core dumped) py.test distributed -v -m gpu --runslow --junitxml="$WORKSPACE/junit-distributed.xml"
09:26:33 Build step 'Execute shell' marked build as failure
```

cc @charlesbluca @quasiben @dask/gpu

### PR DESCRIPTION
**Pull request by pentschev**
Resetting CUDA contexts during a running process may have unintended consequences on third-party libraries -- e.g., CuPy -- that store state based on the context. Therefore, prevent destroying CUDA context for now.

Additionally fix cuDF failure due to a `FutureWarning`.

Closes #8194 

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
It seems gpuCI is failing to resolve github.com, I've raised an internal issue to report that.

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
> It seems gpuCI is failing to resolve github.com, I've raised an internal issue to report that.

This is now resolved.

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

File: continuous_integration/gpuci/build.sh [hunk 1]
```diff
@@ -40,6 +40,8 @@ gpuci_logger "Activate conda env"
 . /opt/conda/etc/profile.d/conda.sh
 conda activate dask
 
+mamba install -y 'aws-sdk-cpp<1.11'
```
Comment (jrbourbeau) [inline continuous_integration/gpuci/build.sh:43]: Is this due to some upstream issue? The actual change here looks totally fine, but it might be worth a comment with extra context

**Review by jrbourbeau — COMMENTED** [review]
Thanks @pentschev! So looks like gpuCI completed successfully three times in a row, is that right?

**Comment by pentschev** [comment]
> Thanks @pentschev! So looks like gpuCI completed successfully three times in a row, is that right?

Yes, that's right. I was rerunning multiple times to confirm. 😄

File: continuous_integration/gpuci/build.sh (hunk 1 above)
Comment (pentschev) [reply continuous_integration/gpuci/build.sh:43]: Indeed, this is due to https://github.com/aws/aws-sdk-cpp/issues/2681, but the change here was just to test/confirm this. For now we will likely resolve the issue via https://github.com/rapidsai/cudf/pull/14173 and revert this change here.

Sorry for not commenting here earlier, I was trying to get this in before bringing people in to review the changes here. 🙂

Comment (jrbourbeau) [reply continuous_integration/gpuci/build.sh:43]: No worries. I just noticed that https://github.com/rapidsai/cudf/pull/14173 is merged -- does that mean we no longer need this here?

**Review by jrbourbeau — APPROVED** [review]
Thanks for fixing @pentschev! I left one non-blocking comment about possibly removing the `aws-sdk-cpp` pin, but it's not critical

File: continuous_integration/gpuci/build.sh (hunk 1 above)
Comment (pentschev) [reply continuous_integration/gpuci/build.sh]: It does now, we first had to fix some issues (mark old cuDF packages as broken and build new gpuCI docker images). I [reverted the `aws-sdk-cpp` changes](https://github.com/dask/distributed/pull/8201/commits/119dc1417ae2826e560096d8873aef1a5e82dd54) now, we just need to wait and see if everything passes and we should be good to merge this. 🙂

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
Alright, gpuCI tests now passed 3 times in a row. I think this should be good to go @jrbourbeau @charlesbluca @quasiben @wence- .

Given we're not changing anything that's running on non-gpuCI tests I don't think any of them are related to this PR. In case anybody sees some correlation I do not, failing tests are summarized below:

```
FAILED tests/test_explicit_comms.py::test_dataframe_shuffle[ucx-cudf-3] - AssertionError: assert not 1
 +  where 1 = <SpawnProcess name='SpawnProcess-15' pid=8047 parent=808 stopped exitcode=1>.exitcode
FAILED distributed/shuffle/tests/test_shuffle.py::test_closed_worker_during_unpack - AssertionError: assert 'shuffle' not in 'shuffle-711...5ab91499-213'
  'shuffle' is contained here:
    shuffle-711a259b679cd132c6eb25b25ab91499-213
  ? +++++++
FAILED distributed/shuffle/tests/test_shuffle.py::test_crashed_worker_after_shuffle - UserWarning: Timed out waiting for sampling thread.
FAILED distributed/tests/test_variable.py::test_race - TimeoutError
FAILED distributed/tests/test_client.py::test_forward_logging - AssertionError: {<Nanny: None, threads: 2>: <Status.closed: 'closed'>, <Nanny: tcp://127.0.0.1:57566, threads: 1>: <Status.closing: 'closing'>}
assert False
```

**Review by charlesbluca — APPROVED** [review]

**Comment by pentschev** [comment]
Thanks @jrbourbeau for reporting/merging and @charlesbluca for the help in debugging and creating new gpuCI images for this. 🙂
